// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/unit/controllers/tikets_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i10;

import 'package:frontend/app/data/models/tiket_model.dart' as _i8;
import 'package:frontend/app/data/models/user_model.dart' as _i7;
import 'package:frontend/app/services/api_service.dart' as _i4;
import 'package:frontend/app/services/auth_service.dart' as _i3;
import 'package:get/get.dart' as _i2;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetHttpClient_1 extends _i1.SmartFake implements _i2.GetHttpClient {
  _FakeGetHttpClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_2<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetSocket_4 extends _i1.SmartFake implements _i2.GetSocket {
  _FakeGetSocket_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraphQLResponse_5<T1> extends _i1.SmartFake
    implements _i2.GraphQLResponse<T1> {
  _FakeGraphQLResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_6 extends _i1.SmartFake implements _i3.AuthResult {
  _FakeAuthResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i4.ApiService {
  @override
  bool get allowAutoSignedCert =>
      (super.noSuchMethod(
            Invocation.getter(#allowAutoSignedCert),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get userAgent =>
      (super.noSuchMethod(
            Invocation.getter(#userAgent),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#userAgent),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#userAgent),
            ),
          )
          as String);

  @override
  bool get sendUserAgent =>
      (super.noSuchMethod(
            Invocation.getter(#sendUserAgent),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get defaultContentType =>
      (super.noSuchMethod(
            Invocation.getter(#defaultContentType),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#defaultContentType),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#defaultContentType),
            ),
          )
          as String);

  @override
  bool get followRedirects =>
      (super.noSuchMethod(
            Invocation.getter(#followRedirects),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get maxRedirects =>
      (super.noSuchMethod(
            Invocation.getter(#maxRedirects),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get maxAuthRetries =>
      (super.noSuchMethod(
            Invocation.getter(#maxAuthRetries),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeout)),
            returnValueForMissingStub: _FakeDuration_0(
              this,
              Invocation.getter(#timeout),
            ),
          )
          as Duration);

  @override
  bool get withCredentials =>
      (super.noSuchMethod(
            Invocation.getter(#withCredentials),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i2.GetSocket> get sockets =>
      (super.noSuchMethod(
            Invocation.getter(#sockets),
            returnValue: <_i2.GetSocket>[],
            returnValueForMissingStub: <_i2.GetSocket>[],
          )
          as List<_i2.GetSocket>);

  @override
  _i2.GetHttpClient get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeGetHttpClient_1(
              this,
              Invocation.getter(#httpClient),
            ),
            returnValueForMissingStub: _FakeGetHttpClient_1(
              this,
              Invocation.getter(#httpClient),
            ),
          )
          as _i2.GetHttpClient);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(
            Invocation.getter(#isDisposed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set allowAutoSignedCert(bool? _allowAutoSignedCert) => super.noSuchMethod(
    Invocation.setter(#allowAutoSignedCert, _allowAutoSignedCert),
    returnValueForMissingStub: null,
  );

  @override
  set userAgent(String? _userAgent) => super.noSuchMethod(
    Invocation.setter(#userAgent, _userAgent),
    returnValueForMissingStub: null,
  );

  @override
  set sendUserAgent(bool? _sendUserAgent) => super.noSuchMethod(
    Invocation.setter(#sendUserAgent, _sendUserAgent),
    returnValueForMissingStub: null,
  );

  @override
  set baseUrl(String? _baseUrl) => super.noSuchMethod(
    Invocation.setter(#baseUrl, _baseUrl),
    returnValueForMissingStub: null,
  );

  @override
  set defaultContentType(String? _defaultContentType) => super.noSuchMethod(
    Invocation.setter(#defaultContentType, _defaultContentType),
    returnValueForMissingStub: null,
  );

  @override
  set followRedirects(bool? _followRedirects) => super.noSuchMethod(
    Invocation.setter(#followRedirects, _followRedirects),
    returnValueForMissingStub: null,
  );

  @override
  set maxRedirects(int? _maxRedirects) => super.noSuchMethod(
    Invocation.setter(#maxRedirects, _maxRedirects),
    returnValueForMissingStub: null,
  );

  @override
  set maxAuthRetries(int? _maxAuthRetries) => super.noSuchMethod(
    Invocation.setter(#maxAuthRetries, _maxAuthRetries),
    returnValueForMissingStub: null,
  );

  @override
  set defaultDecoder(_i2.Decoder<dynamic>? _defaultDecoder) =>
      super.noSuchMethod(
        Invocation.setter(#defaultDecoder, _defaultDecoder),
        returnValueForMissingStub: null,
      );

  @override
  set timeout(Duration? _timeout) => super.noSuchMethod(
    Invocation.setter(#timeout, _timeout),
    returnValueForMissingStub: null,
  );

  @override
  set trustedCertificates(List<_i2.TrustedCertificate>? _trustedCertificates) =>
      super.noSuchMethod(
        Invocation.setter(#trustedCertificates, _trustedCertificates),
        returnValueForMissingStub: null,
      );

  @override
  set findProxy(String Function(Uri)? _findProxy) => super.noSuchMethod(
    Invocation.setter(#findProxy, _findProxy),
    returnValueForMissingStub: null,
  );

  @override
  set withCredentials(bool? _withCredentials) => super.noSuchMethod(
    Invocation.setter(#withCredentials, _withCredentials),
    returnValueForMissingStub: null,
  );

  @override
  set sockets(List<_i2.GetSocket>? _sockets) => super.noSuchMethod(
    Invocation.setter(#sockets, _sockets),
    returnValueForMissingStub: null,
  );

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i2.Response<dynamic>> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> register(
    _i7.RegisterRequest? registerData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [registerData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#register, [registerData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#register, [registerData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#refreshToken, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#refreshToken, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> changePassword(
    _i7.ChangePasswordRequest? changePasswordData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [changePasswordData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#changePassword, [changePasswordData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#changePassword, [changePasswordData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> updateProfile(
    _i7.UpdateProfileRequest? profileData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profileData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateProfile, [profileData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateProfile, [profileData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(this, Invocation.method(#logout, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(this, Invocation.method(#logout, [])),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> patchJson(
    String? url,
    dynamic body, {
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchJson,
              [url, body],
              {#contentType: contentType, #headers: headers, #query: query},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #patchJson,
                  [url, body],
                  {#contentType: contentType, #headers: headers, #query: query},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #patchJson,
                  [url, body],
                  {#contentType: contentType, #headers: headers, #query: query},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getUsers({Map<String, String>? query}) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {#query: query}),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUsers, [], {#query: query}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUsers, [], {#query: query}),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> createUser(
    Map<String, dynamic>? userData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [userData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createUser, [userData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createUser, [userData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> updateUser(
    int? userId,
    Map<String, dynamic>? userData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [userId, userData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateUser, [userId, userData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateUser, [userId, userData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> deleteUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteUser, [userId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteUser, [userId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getUserById(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUserById, [userId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUserById, [userId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#getUserStats, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUserStats, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUserStats, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> toggleUserStatus(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleUserStatus, [userId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#toggleUserStatus, [userId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#toggleUserStatus, [userId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getKaryawans({
    Map<String, String>? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getKaryawans, [], {#query: query}),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKaryawans, [], {#query: query}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKaryawans, [], {#query: query}),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> createKaryawan(
    Map<String, dynamic>? karyawanData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createKaryawan, [karyawanData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createKaryawan, [karyawanData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createKaryawan, [karyawanData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> updateKaryawan(
    int? karyawanId,
    Map<String, dynamic>? karyawanData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateKaryawan, [karyawanId, karyawanData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateKaryawan, [karyawanId, karyawanData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateKaryawan, [karyawanId, karyawanData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> deleteKaryawan(int? karyawanId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKaryawan, [karyawanId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteKaryawan, [karyawanId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteKaryawan, [karyawanId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getKaryawanById(int? karyawanId) =>
      (super.noSuchMethod(
            Invocation.method(#getKaryawanById, [karyawanId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKaryawanById, [karyawanId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKaryawanById, [karyawanId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getRoles({Map<String, String>? query}) =>
      (super.noSuchMethod(
            Invocation.method(#getRoles, [], {#query: query}),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getRoles, [], {#query: query}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getRoles, [], {#query: query}),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getRoleOptions() =>
      (super.noSuchMethod(
            Invocation.method(#getRoleOptions, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getRoleOptions, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getRoleOptions, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getRoleStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRoleStats, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getRoleStats, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getRoleStats, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> createRole(
    Map<String, dynamic>? roleData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRole, [roleData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createRole, [roleData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createRole, [roleData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> updateRole(
    int? roleId,
    Map<String, dynamic>? roleData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRole, [roleId, roleData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateRole, [roleId, roleData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateRole, [roleId, roleData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> deleteRole(int? roleId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRole, [roleId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteRole, [roleId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteRole, [roleId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getRoleById(int? roleId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoleById, [roleId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getRoleById, [roleId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getRoleById, [roleId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getUnits({Map<String, String>? query}) =>
      (super.noSuchMethod(
            Invocation.method(#getUnits, [], {#query: query}),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUnits, [], {#query: query}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUnits, [], {#query: query}),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> createUnit(
    Map<String, dynamic>? unitData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUnit, [unitData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createUnit, [unitData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createUnit, [unitData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> updateUnit(
    int? unitId,
    Map<String, dynamic>? unitData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUnit, [unitId, unitData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateUnit, [unitId, unitData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateUnit, [unitId, unitData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> deleteUnit(int? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUnit, [unitId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteUnit, [unitId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteUnit, [unitId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getUnitById(int? unitId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnitById, [unitId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUnitById, [unitId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUnitById, [unitId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getStatuses({Map<String, String>? query}) =>
      (super.noSuchMethod(
            Invocation.method(#getStatuses, [], {#query: query}),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getStatuses, [], {#query: query}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getStatuses, [], {#query: query}),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getStatusOptions() =>
      (super.noSuchMethod(
            Invocation.method(#getStatusOptions, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getStatusOptions, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getStatusOptions, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getStatusStats() =>
      (super.noSuchMethod(
            Invocation.method(#getStatusStats, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getStatusStats, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getStatusStats, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> reorderStatuses(
    List<Map<String, dynamic>>? orderData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reorderStatuses, [orderData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#reorderStatuses, [orderData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#reorderStatuses, [orderData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> createStatus(
    Map<String, dynamic>? statusData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStatus, [statusData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createStatus, [statusData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createStatus, [statusData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> updateStatus(
    int? statusId,
    Map<String, dynamic>? statusData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, [statusId, statusData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateStatus, [statusId, statusData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateStatus, [statusId, statusData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> deleteStatus(int? statusId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStatus, [statusId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteStatus, [statusId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteStatus, [statusId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getStatusById(int? statusId) =>
      (super.noSuchMethod(
            Invocation.method(#getStatusById, [statusId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getStatusById, [statusId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getStatusById, [statusId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getTikets({Map<String, String>? query}) =>
      (super.noSuchMethod(
            Invocation.method(#getTikets, [], {#query: query}),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getTikets, [], {#query: query}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getTikets, [], {#query: query}),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getTiketStats() =>
      (super.noSuchMethod(
            Invocation.method(#getTiketStats, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getTiketStats, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getTiketStats, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> createTiket(
    _i8.CreateTiketRequest? tiketData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTiket, [tiketData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createTiket, [tiketData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createTiket, [tiketData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> updateTiket(
    int? tiketId,
    _i8.UpdateTiketRequest? tiketData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTiket, [tiketId, tiketData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateTiket, [tiketId, tiketData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateTiket, [tiketId, tiketData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> deleteTiket(int? tiketId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTiket, [tiketId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteTiket, [tiketId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteTiket, [tiketId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getTiketById(int? tiketId) =>
      (super.noSuchMethod(
            Invocation.method(#getTiketById, [tiketId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getTiketById, [tiketId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getTiketById, [tiketId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> assignTiketToUnit(
    int? tiketId,
    int? unitId, {
    int? karyawanId,
    String? komentar,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #assignTiketToUnit,
              [tiketId, unitId],
              {#karyawanId: karyawanId, #komentar: komentar},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #assignTiketToUnit,
                  [tiketId, unitId],
                  {#karyawanId: karyawanId, #komentar: komentar},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #assignTiketToUnit,
                  [tiketId, unitId],
                  {#karyawanId: karyawanId, #komentar: komentar},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> assignTiketToKaryawan(
    int? tiketId,
    int? karyawanId, {
    String? komentar,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #assignTiketToKaryawan,
              [tiketId, karyawanId],
              {#komentar: komentar},
            ),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #assignTiketToKaryawan,
                  [tiketId, karyawanId],
                  {#komentar: komentar},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(
                  #assignTiketToKaryawan,
                  [tiketId, karyawanId],
                  {#komentar: komentar},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> updateTiketStatus(
    int? tiketId,
    _i8.UpdateStatusRequest? statusData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTiketStatus, [tiketId, statusData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateTiketStatus, [tiketId, statusData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateTiketStatus, [tiketId, statusData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getKomentars(
    int? tiketId, {
    Map<String, String>? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getKomentars, [tiketId], {#query: query}),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKomentars, [tiketId], {#query: query}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKomentars, [tiketId], {#query: query}),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> createKomentar(
    int? tiketId,
    _i8.CreateKomentarRequest? komentarData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createKomentar, [tiketId, komentarData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createKomentar, [tiketId, komentarData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#createKomentar, [tiketId, komentarData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> updateKomentar(
    int? komentarId,
    Map<String, dynamic>? komentarData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateKomentar, [komentarId, komentarData]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateKomentar, [komentarId, komentarData]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateKomentar, [komentarId, komentarData]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> deleteKomentar(int? komentarId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKomentar, [komentarId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteKomentar, [komentarId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#deleteKomentar, [komentarId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getKomentarById(int? komentarId) =>
      (super.noSuchMethod(
            Invocation.method(#getKomentarById, [komentarId]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKomentarById, [komentarId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKomentarById, [komentarId]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getKomentarStats() =>
      (super.noSuchMethod(
            Invocation.method(#getKomentarStats, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKomentarStats, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKomentarStats, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getAdminDashboardStats() =>
      (super.noSuchMethod(
            Invocation.method(#getAdminDashboardStats, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getAdminDashboardStats, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getAdminDashboardStats, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getAdminReports({
    String? dateFrom,
    String? dateTo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAdminReports, [], {
              #dateFrom: dateFrom,
              #dateTo: dateTo,
            }),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getAdminReports, [], {
                  #dateFrom: dateFrom,
                  #dateTo: dateTo,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getAdminReports, [], {
                  #dateFrom: dateFrom,
                  #dateTo: dateTo,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getManagerDashboardStats() =>
      (super.noSuchMethod(
            Invocation.method(#getManagerDashboardStats, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getManagerDashboardStats, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getManagerDashboardStats, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getManagerUnitPerformance() =>
      (super.noSuchMethod(
            Invocation.method(#getManagerUnitPerformance, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getManagerUnitPerformance, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getManagerUnitPerformance, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getKaryawanDashboardStats() =>
      (super.noSuchMethod(
            Invocation.method(#getKaryawanDashboardStats, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKaryawanDashboardStats, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKaryawanDashboardStats, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getKaryawanMyTikets() =>
      (super.noSuchMethod(
            Invocation.method(#getKaryawanMyTikets, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKaryawanMyTikets, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getKaryawanMyTikets, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getDireksiDashboardStats() =>
      (super.noSuchMethod(
            Invocation.method(#getDireksiDashboardStats, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getDireksiDashboardStats, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getDireksiDashboardStats, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getDireksiPerformanceReports() =>
      (super.noSuchMethod(
            Invocation.method(#getDireksiPerformanceReports, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getDireksiPerformanceReports, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getDireksiPerformanceReports, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getUserDashboardStats() =>
      (super.noSuchMethod(
            Invocation.method(#getUserDashboardStats, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUserDashboardStats, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUserDashboardStats, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> getUserMyTikets() =>
      (super.noSuchMethod(
            Invocation.method(#getUserMyTikets, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUserMyTikets, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#getUserMyTikets, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<T>> get<T>(
    String? url, {
    Map<String, String>? headers,
    String? contentType,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [url],
              {
                #headers: headers,
                #contentType: contentType,
                #query: query,
                #decoder: decoder,
              },
            ),
            returnValue: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #get,
                  [url],
                  {
                    #headers: headers,
                    #contentType: contentType,
                    #query: query,
                    #decoder: decoder,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #get,
                  [url],
                  {
                    #headers: headers,
                    #contentType: contentType,
                    #query: query,
                    #decoder: decoder,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<T>>);

  @override
  _i6.Future<_i2.Response<T>> post<T>(
    String? url,
    dynamic body, {
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
    _i2.Progress? uploadProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url, body],
              {
                #contentType: contentType,
                #headers: headers,
                #query: query,
                #decoder: decoder,
                #uploadProgress: uploadProgress,
              },
            ),
            returnValue: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #post,
                  [url, body],
                  {
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #post,
                  [url, body],
                  {
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<T>>);

  @override
  _i6.Future<_i2.Response<T>> put<T>(
    String? url,
    dynamic body, {
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
    _i2.Progress? uploadProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url, body],
              {
                #contentType: contentType,
                #headers: headers,
                #query: query,
                #decoder: decoder,
                #uploadProgress: uploadProgress,
              },
            ),
            returnValue: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #put,
                  [url, body],
                  {
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #put,
                  [url, body],
                  {
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<T>>);

  @override
  _i6.Future<_i2.Response<T>> patch<T>(
    String? url,
    dynamic body, {
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
    _i2.Progress? uploadProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url, body],
              {
                #contentType: contentType,
                #headers: headers,
                #query: query,
                #decoder: decoder,
                #uploadProgress: uploadProgress,
              },
            ),
            returnValue: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #patch,
                  [url, body],
                  {
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #patch,
                  [url, body],
                  {
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<T>>);

  @override
  _i6.Future<_i2.Response<T>> request<T>(
    String? url,
    String? method, {
    dynamic body,
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
    _i2.Progress? uploadProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url, method],
              {
                #body: body,
                #contentType: contentType,
                #headers: headers,
                #query: query,
                #decoder: decoder,
                #uploadProgress: uploadProgress,
              },
            ),
            returnValue: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #request,
                  [url, method],
                  {
                    #body: body,
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #request,
                  [url, method],
                  {
                    #body: body,
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<T>>);

  @override
  _i6.Future<_i2.Response<T>> delete<T>(
    String? url, {
    Map<String, String>? headers,
    String? contentType,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {
                #headers: headers,
                #contentType: contentType,
                #query: query,
                #decoder: decoder,
              },
            ),
            returnValue: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {
                    #headers: headers,
                    #contentType: contentType,
                    #query: query,
                    #decoder: decoder,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {
                    #headers: headers,
                    #contentType: contentType,
                    #query: query,
                    #decoder: decoder,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<T>>);

  @override
  _i2.GetSocket socket(
    String? url, {
    Duration? ping = const Duration(seconds: 5),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#socket, [url], {#ping: ping}),
            returnValue: _FakeGetSocket_4(
              this,
              Invocation.method(#socket, [url], {#ping: ping}),
            ),
            returnValueForMissingStub: _FakeGetSocket_4(
              this,
              Invocation.method(#socket, [url], {#ping: ping}),
            ),
          )
          as _i2.GetSocket);

  @override
  _i6.Future<_i2.GraphQLResponse<T>> query<T>(
    String? query, {
    String? url,
    Map<String, dynamic>? variables,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [query],
              {#url: url, #variables: variables, #headers: headers},
            ),
            returnValue: _i6.Future<_i2.GraphQLResponse<T>>.value(
              _FakeGraphQLResponse_5<T>(
                this,
                Invocation.method(
                  #query,
                  [query],
                  {#url: url, #variables: variables, #headers: headers},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.GraphQLResponse<T>>.value(
              _FakeGraphQLResponse_5<T>(
                this,
                Invocation.method(
                  #query,
                  [query],
                  {#url: url, #variables: variables, #headers: headers},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.GraphQLResponse<T>>);

  @override
  _i6.Future<_i2.GraphQLResponse<T>> mutation<T>(
    String? mutation, {
    String? url,
    Map<String, dynamic>? variables,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #mutation,
              [mutation],
              {#url: url, #variables: variables, #headers: headers},
            ),
            returnValue: _i6.Future<_i2.GraphQLResponse<T>>.value(
              _FakeGraphQLResponse_5<T>(
                this,
                Invocation.method(
                  #mutation,
                  [mutation],
                  {#url: url, #variables: variables, #headers: headers},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.GraphQLResponse<T>>.value(
              _FakeGraphQLResponse_5<T>(
                this,
                Invocation.method(
                  #mutation,
                  [mutation],
                  {#url: url, #variables: variables, #headers: headers},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.GraphQLResponse<T>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(
            Invocation.getter(#listeners),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i3.AuthResult> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_6(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_6(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void updateUserData(_i7.User? updatedUser) => super.noSuchMethod(
    Invocation.method(#updateUserData, [updatedUser]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> tryAutoLogin() =>
      (super.noSuchMethod(
            Invocation.method(#tryAutoLogin, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void handleSessionExpired() => super.noSuchMethod(
    Invocation.method(#handleSessionExpired, []),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Disposer addListener(_i9.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i9.Disposer);

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i10.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Disposer addListenerId(Object? key, _i9.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i9.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
